routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 *  you can see the list of all the routes with all details by typing,
 *  php artisan route:list on the commandline. also change your directory to 
 *  this project directory when doing so.
 */

/**
 * Dashboard Route(s)
 * 
 */
Route::get('/dashboard','DashboardController@index')->name('dashboard');

/**
 *  Departments Route(s)
 * 
 */
Route::resource('/departments','DepartmentsController');
Route::post('/departments/search','DepartmentsController@search')->name('departments.search');

/**
 *  Countries Route(s)
 */
Route::resource('/countries','CountriesController');
Route::post('/countries/search','CountriesController@search')->name('countries.search');

/**
 *  Cities Route(s)
 */
Route::resource('/cities','CitiesController');
Route::post('/cities/search','CitiesController@search')->name('cities.search');

/**
 *  Salaries Route(s)
 */
Route::resource('/salaries','SalariesController');
Route::post('/salaries/search','SalariesController@search')->name('salaries.search');

/**
 *  Divisions Route(s)
 */
Route::resource('/divisions','DivisionsController');
Route::post('/divisions/search','DivisionsController@search')->name('divisions.search');

/**
 *  States Route(s)
 */
Route::resource('/states','StatesController');
Route::post('/states/search','StatesController@search')->name('states.search');

/**
 *  States Route(s)
 */
Route::resource('/employees','EmployeesController');

Route::post('employees/search','EmployeesController@search')->name('employees.search');

/**
 *  Admins Route(s)
 */
Route::resource('/admins','AdminsController');
Route::post('/admins','AdminsController@search')->name('admins.search');
Route::post('/admins/create','AdminsController@store')->name('admins.store');

/**
 *  Auth Route(s)
 */

//show the login view
Route::get('/','AuthController@index')->name('login')->middleware('guest');

//Authenticate a user
Route::post('/','AuthController@authenticate')->name('auth.authenticate');

//logout the user
Route::get('/logout','AuthController@logout')->name('auth.logout')->middleware('auth');

//show user details
Route::get('/admin','AuthController@show')->name('auth.show')->middleware('auth');

Route::get('/password/reset','ResetPassword\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email','ResetPassword\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}','ResetPassword\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset','ResetPassword\ResetPasswordController@reset');

/**
 *  Reports Route(s)
 */

//Show Reports View
Route::get('/reports','ReportsController@index')->name('reports.index');

//Generate PDF
Route::post('/reports/pdf','ReportsController@makeReport')->name('reports.make');

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    //
}

app/Http/Controllers/CitiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\City;

class CitiesController extends Controller
{
    /**
     *  Only authenticated users can access this controller
     */
    public function __construct(){
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /**
         *  read all the comments from DepartmentsController
         *  they are all the same.
         */
        
        $cities = City::Paginate(5);
        return view('sys_mg.cities.index')->with('cities',$cities);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sys_mg.cities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'city_name' => 'required|min:2',
            'zip_code' => 'required|min:4|unique:cities'
        ]);
        $city = new City();
        $city->city_name = $request->input('city_name');
        $city->zip_code = $request->input('zip_code');
        $city->save();
        return redirect('/cities')->with('info','City has been created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $city = City::find($id);
        return view('sys_mg.cities.edit')->with('city',$city);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'city_name' => 'required|min:2',
            'zip_code' => 'required|min:4|unique:cities,zip_code,'.$id
        ]);
        $city = City::find($id);
        $city->city_name = $request->input('city_name');
        $city->zip_code = $request->input('zip_code');
        $city->save();
        return redirect('/cities')->with('info','Selected city has been updated!');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $city = City::find($id);
        $city->delete();
        return redirect('/cities')->with('info','Selected city has been deleted!');
    }

    /**
     *  Search For Resource(s)
     * 
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request){
        $this->validate($request,[
            'search' => 'required'
        ]);
        $str = $request->input('search');
        $cities = City::where( 'city_name' , 'LIKE' , '%'.$str.'%' )
            ->orderBy('city_name','asc')
            ->paginate(4);
        return view('sys_mg.cities.index')->with([ 'cities' => $cities ,'search' => true ]);
    }
}

resources/views/sys_mg/cities/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">
                <h4 class="center grey-text text-darken-2 card-title">Add City</h4>
                <div class="card-content">
                    <div class="row">
                        <form action="{{route('cities.store')}}" method="POST">
                            <div class="input-field no-margin">
                                <i class="material-icons prefix">location_city</i>
                                <input type="text" name="city_name" id="city_name" class="validate" value="{{Request::old('city_name') ? : ''}}">
                                <label for="city_name">City Name</label>
                                <span class="{{$errors->has('city_name') ? 'helper-text red-text' : '' }}">{{$errors->first('city_name')}}</span>
                            </div>
                            <div class="input-field">
                                <i class="material-icons prefix">vpn_lock</i>
                                <input type="number" name="zip_code" id="zip_code" class="validate" value="{{Request::old('zip_code') ? : ''}}">
                                <label for="zip_code">Zip Code</label>
                                <span class="{{$errors->has('zip_code') ? 'helper-text red-text' : '' }}">{{$errors->first('zip_code')}}</span>
                            </div>
                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Add</button>
                        </form>
                    </div>
                </div>
                <div class="card-action">
                    <a href="/cities">Go Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sys_mg/cities/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="card col s12 m8 offset-m2 l8 offset-l2 xl8 offset-xl2 card-mt-15">
                <h4 class="center grey-text text-darken-2 card-title">Update City</h4>
                <div class="card-content">
                    <div class="row">
                        <form action="{{route('cities.update',$city->id)}}" method="POST">
                            <div class="input-field">
                                <i class="material-icons prefix">location_city</i>    
                                <input type="text" name="city_name" id="city_name" value="{{Request::old('city_name') ? : $city->city_name}}">
                                <label for="city_name">City Name</label>
                                <span class="{{$errors->has('city_name') ? 'helper-text red-text' : ''}}">{{$errors->first('city_name')}}</span>
                            </div>
                            <div class="input-field">
                                <i class="material-icons prefix">vpn_lock</i>
                                <input type="number" name="zip_code" id="zip_code" class="validate" value="{{Request::old('zip_code') ? : $city->zip_code}}">
                                <label for="zip_code">Zip Code</label>
                                <span class="{{$errors->has('zip_code') ? 'helper-text red-text' : '' }}">{{$errors->first('zip_code')}}</span>
                            </div>
                            @method('PUT')
                            @csrf()
                            <button type="submit" class="btn waves-effect waves-light col s6 offset-s3 m4 offset-m4 l4 offset-l4 xl4-offset-xl4">Update</button>
                        </form>
                    </div>
                    <div class="card-action">
                        <a href="/cities">Go Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sys_mg/cities/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h4 class="grey-text text-darken-2 center">City Management</h4>

    {{-- Include the searh component with with title and route --}}
    @component('sys_mg.inc.search',['title' => 'City' , 'route' => 'cities.search'])
    @endcomponent

    <div class="row">
        <!-- Show All Cities List as a Card -->
        <div class="card col s12 m12 l12 xl12">
            <div class="card-content">
                <div class="row">
                    <h5 class="pl-15 grey-text text-darken-2">Cities List</h5>
                    <!-- Table that shows Cities List -->
                    <table class="responsive-table col s12 m12 l12 xl12">
                        <thead class="grey-text text-darken-1">
                            <tr>
                                <th>ID</th>
                                <th>City Name</th>
                                <th>Zip Code</th>
                                <th>Created at</th>
                                <th>Updated at</th>
                                <th>Options</th>
                            </tr>
                        </thead>
                        <tbody id="item-table">
                            <!-- Check if there are any cities to render in view -->
                            @if($cities->count())
                                @foreach($cities as $city)
                                    <tr>
                                        <td>{{$city->id}}</td>
                                        <td>{{$city->city_name}}</td>
                                        <td>{{$city->zip_code}}</td>
                                        <td>{{$city->created_at}}</td>
                                        <td>{{$city->updated_at}}</td>
                                        <td>
                                            <div class="row mb-0">
                                              <div class="col">
                                                    <a href="{{route('cities.edit',$city->id)}}" class="btn btn-floating btn-small waves=effect waves-light orange"><i class="material-icons">mode_edit</i></a>
                                                </div>
                                                <div class="col">
                                                    <form onsubmit="return confirm('Do you really want to delete?');" action="{{route('cities.destroy',$city->id)}}" method="POST">
                                                        @method('DELETE')
                                                        @csrf()
                                                        <button type="submit" class="btn btn-floating btn-small waves=effect waves-light red"><i class="material-icons">delete</i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <!-- if there are no cities then show this message -->
                                <tr>
                                    <td colspan="5"><h6 class="grey-text text-darken-2 center">No Cities  found!</h6></td>
                                </tr>
                            @endif
                            @if(isset($search))
                                <tr>
                                    <td colspan="4">
                                        <a href="/cities" class="right">Show All</a>
                                    </td>
                                </tr>
                            @endif
                        </tbody>
                    </table>
                    <!-- Cities Table END -->
                </div>
                <!-- Show Pagination Links -->
                <div class="center">
                  {{$cities->links('vendor.pagination.default',['paginator' => $cities])}}
                </div>
            </div>
        </div>
        <!-- Card END -->
    </div>
</div>


<!-- This is the button that is located at the right bottom, that navigates us to city.create view -->
<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves=effect waves-light red" href="{{route('cities.create')}}">
        <i class="large material-icons">add</i>
    </a>
</div> 
@endsection